name: "[DEV] Build Artifacts"
on: 
  push:
    branches:
      - master

jobs:
  build-ios:
    name: iOS DEV build
    runs-on: macos-14
    environment: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          echo "${{vars.ENV_VAR}}" >> .env.local

      - name: Install dependencies
        run: yarn install

      - name: Expo prebuild
        run: yarn prebuild

      - name: Archive
        run: |
          cd ios
          xcodebuild -workspace CostCount.xcworkspace -scheme CostCount -configuration Release clean archive -archivePath unsigned.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      
      - name: Bundle
        run: |
          cd ios/unsigned.xcarchive/Products
          mv Applications Payload
          zip -r unsigned.ipa Payload
      
      - name: Collect ipa artifact
        uses: actions/upload-artifact@v2
        with:
          name: unsigned-ipa
          path: ios/unsigned.xcarchive/Products/unsigned.ipa

  build-android:    
    name: Android DEV build
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          echo "${{vars.ENV_VAR}}" >> .env.local

      - name: Install dependencies
        run: yarn install

      - name: Expo prebuild
        run: yarn prebuild

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.0'
          distribution: 'microsoft'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle build
        run: |
          cd android
          ./gradlew build

      - name: find apk artifact
        run: |
          cd android\app\build\outputs\apk\debug
          ls

      - name: Collect apk artifact
        uses: actions/upload-artifact@v2
        with:
          name: unsigned-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
        